project:
  type: website
  output-dir: _site

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: 主页
      - href: about.qmd
        text: 关于我

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false