project:
  type: website
  output-dir: _site
  resources:
    - data

website:
  title: ""

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    title-block: false
    include-in-header:
      - header.html
